//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartFunds.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smartFunds.Common.Resources.Enum", typeof(Enum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các khoản chi phí lớn.
        /// </summary>
        public static string BigExpenses {
            get {
                return ResourceManager.GetString("BigExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tỷ.
        /// </summary>
        public static string Billion {
            get {
                return ResourceManager.GetString("Billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua CCQ.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngày.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiền cho khách hàng.
        /// </summary>
        public static string DealCustomer {
            get {
                return ResourceManager.GetString("DealCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiền quỹ.
        /// </summary>
        public static string DealFund {
            get {
                return ResourceManager.GetString("DealFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 tháng.
        /// </summary>
        public static string Duration12Month {
            get {
                return ResourceManager.GetString("Duration12Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 năm.
        /// </summary>
        public static string Duration2Year {
            get {
                return ResourceManager.GetString("Duration2Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 tháng.
        /// </summary>
        public static string Duration3Month {
            get {
                return ResourceManager.GetString("Duration3Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 năm.
        /// </summary>
        public static string Duration5Year {
            get {
                return ResourceManager.GetString("Duration5Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 tháng.
        /// </summary>
        public static string Duration6Month {
            get {
                return ResourceManager.GetString("Duration6Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi thường gặp.
        /// </summary>
        public static string FAQCategory1 {
            get {
                return ResourceManager.GetString("FAQCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn người dùng mới.
        /// </summary>
        public static string FAQCategory2 {
            get {
                return ResourceManager.GetString("FAQCategory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 tháng/lần.
        /// </summary>
        public static string Frequency1Month {
            get {
                return ResourceManager.GetString("Frequency1Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 tuần/lần.
        /// </summary>
        public static string Frequency1Week {
            get {
                return ResourceManager.GetString("Frequency1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 tuần/lần.
        /// </summary>
        public static string Frequency2Week {
            get {
                return ResourceManager.GetString("Frequency2Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí mua chứng chỉ quỹ.
        /// </summary>
        public static string FundPurchaseFee {
            get {
                return ResourceManager.GetString("FundPurchaseFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí bán chứng chỉ quỹ.
        /// </summary>
        public static string FundSellFee {
            get {
                return ResourceManager.GetString("FundSellFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lạm phát.
        /// </summary>
        public static string Inflationary {
            get {
                return ResourceManager.GetString("Inflationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu tư và rút tiền.
        /// </summary>
        public static string InvestAndWithdraw {
            get {
                return ResourceManager.GetString("InvestAndWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu tư.
        /// </summary>
        public static string Investment {
            get {
                return ResourceManager.GetString("Investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trừ tiền tự động.
        /// </summary>
        public static string InvestmentMethodAuto {
            get {
                return ResourceManager.GetString("InvestmentMethodAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự đầu tư.
        /// </summary>
        public static string InvestmentMethodManually {
            get {
                return ResourceManager.GetString("InvestmentMethodManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khẩu vị rủi ro.
        /// </summary>
        public static string KVRR {
            get {
                return ResourceManager.GetString("KVRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu tư dài hạn.
        /// </summary>
        public static string LongTermInvestment {
            get {
                return ResourceManager.GetString("LongTermInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triệu.
        /// </summary>
        public static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tháng.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trên.
        /// </summary>
        public static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian cá nhân của bạn.
        /// </summary>
        public static string PersonalTime {
            get {
                return ResourceManager.GetString("PersonalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục đầu tư.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục đầu tư.
        /// </summary>
        public static string PortfolioFund {
            get {
                return ResourceManager.GetString("PortfolioFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biến động giá.
        /// </summary>
        public static string PriceFluctuations {
            get {
                return ResourceManager.GetString("PriceFluctuations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rủi ro so với lợi nhuận.
        /// </summary>
        public static string RiskVersusProfit {
            get {
                return ResourceManager.GetString("RiskVersusProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán CCQ.
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu với SaveNow.
        /// </summary>
        public static string StartWithSaveNow {
            get {
                return ResourceManager.GetString("StartWithSaveNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        public static string TaskStatusNew {
            get {
                return ResourceManager.GetString("TaskStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thực hiện.
        /// </summary>
        public static string TaskStatusProcessing {
            get {
                return ResourceManager.GetString("TaskStatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string TaskStatusSuccess {
            get {
                return ResourceManager.GetString("TaskStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ.
        /// </summary>
        public static string TaskStatusWaiting {
            get {
                return ResourceManager.GetString("TaskStatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string TransactionStatus {
            get {
                return ResourceManager.GetString("TransactionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        public static string TransactionStatusProcessing {
            get {
                return ResourceManager.GetString("TransactionStatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string TransactionStatusSuccess {
            get {
                return ResourceManager.GetString("TransactionStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hình giao dịch.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí duy trì tài khoản.
        /// </summary>
        public static string TransactionTypeAccountFee {
            get {
                return ResourceManager.GetString("TransactionTypeAccountFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiền quỹ.
        /// </summary>
        public static string TransactionTypeAdminInvestment {
            get {
                return ResourceManager.GetString("TransactionTypeAdminInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rút tiền quỹ.
        /// </summary>
        public static string TransactionTypeAdminWithdrawal {
            get {
                return ResourceManager.GetString("TransactionTypeAdminWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu tư.
        /// </summary>
        public static string TransactionTypeInvestment {
            get {
                return ResourceManager.GetString("TransactionTypeInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rút tiền.
        /// </summary>
        public static string TransactionTypeWithdrawal {
            get {
                return ResourceManager.GetString("TransactionTypeWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dưới.
        /// </summary>
        public static string Under {
            get {
                return ResourceManager.GetString("Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiểu biết về các rủi ro.
        /// </summary>
        public static string UnderstandingTheRisks {
            get {
                return ResourceManager.GetString("UnderstandingTheRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví tiền.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí rút tiền.
        /// </summary>
        public static string WithdrawalFee {
            get {
                return ResourceManager.GetString("WithdrawalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rút thông thường.
        /// </summary>
        public static string WithdrawalTypeManually {
            get {
                return ResourceManager.GetString("WithdrawalTypeManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rút nhanh.
        /// </summary>
        public static string WithdrawalTypeQuick {
            get {
                return ResourceManager.GetString("WithdrawalTypeQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to năm.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
